// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ToyService.proto

package net.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string toyName = 1;</code>
   * @return The toyName.
   */
  java.lang.String getToyName();
  /**
   * <code>string toyName = 1;</code>
   * @return The bytes for toyName.
   */
  com.google.protobuf.ByteString
      getToyNameBytes();
}
