// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ToyService.proto

package net.grpc;

public interface RespondOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Respond)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float price = 1;</code>
   * @return The price.
   */
  float getPrice();

  /**
   * <code>int32 success = 2;</code>
   * @return The success.
   */
  int getSuccess();

  /**
   * <code>int32 stock = 3;</code>
   * @return The stock.
   */
  int getStock();
}
