// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ToyService.proto

package net.grpc;

public final class ToyServiceOuterClass {
  private ToyServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Respond_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Respond_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ToyService.proto\"\032\n\007Request\022\017\n\007toyName" +
      "\030\001 \001(\t\"8\n\007Respond\022\r\n\005price\030\001 \001(\002\022\017\n\007succ" +
      "ess\030\002 \001(\005\022\r\n\005stock\030\003 \001(\0052D\n\nToyService\022\033" +
      "\n\005query\022\010.Request\032\010.Respond\022\031\n\003buy\022\010.Req" +
      "uest\032\010.RespondB\014\n\010net.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "ToyName", });
    internal_static_Respond_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Respond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Respond_descriptor,
        new java.lang.String[] { "Price", "Success", "Stock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
